server:
  port: 9999

spring:
  cloud:
    config:
      server:
        git:
          uri: ENC(9Mho31ejNmpZLDCkuLjhZcLj7mkdjyR1xDIT+671bzx+zfbSRT6LGsknXdIeAzAwvu1H1WcNXtXJqMFr2r7Jmg==)
          username: ENC(zlGbwdVMNCmyqnXfpiKCauAY4WlYUsD1rPiRvYaLhmM=)
          password: ENC(R44nTG3Lvb8xvh8RCBZstKdxCOWBLbAf)

#          uri: file://C:\PlayData\config-resource - 로컬용


