server:
  port: 8000

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        # 개별 마이크로서비스 정보를 routes에 기입
        - id: first-service
          uri: http://localhost:8001/
          predicates:
            # http://localhost:8000/second-service/** 와 동일
            - Path=/first-service/**
          filters:
#            - AddRequestHeader=fsreghyml,fsreqhymlv
#            - AddResponseHeader=fsresphyml,fsresphyml
            - CustomFilter

        - id: second-service
          # 실제 요청 url : http://localhost:8002/second-service/...
          uri: http://localhost:8002/
          predicates:
            # http://localhost:8000/second-service/** 와 동일
            - Path=/second-service/**
          filters:
            - CustomFilter2
      default-filters:
        - name: GlobalFilter
          args:
            message: Global Filter Default Message
            pre: true
            post: true

